name: Protect main

on:
  push:
    branches: [main]

jobs:
  prevent-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is allowed
        run: |
          # Allow deploy workflow pushes
          if [[ "${{ github.event.head_commit.message }}" == *"Deploy to GitHub Pages"* ]]; then
            echo "Allowing deploy workflow push"
            exit 0
          fi

          # Block all other direct pushes
          echo "Error: Direct pushes to main are blocked. Use Pull Requests."
          echo "Include 'Deploy to GitHub Pages' in commit message for deployments."
          exit 1
